DROP TABLE IF EXISTS BOOKS;

CREATE TABLE BOOKS (
  ISBN VARCHAR(250)  PRIMARY KEY,
  TITLE VARCHAR(250) NOT NULL,
  AUTHOR VARCHAR(250) NOT NULL,
  PUBLICATION_YEAR VARCHAR(250) NOT NULL,
  PUBLISHER VARCHAR(250) NOT NULL,
  ADDED_ON DATE NOT NULL,
  UPDATED_ON DATE NOT NULL,
  IS_LENT TINYINT(1) NOT NULL,
  LENT_TO VARCHAR(250),
);
